server:
  servlet:
    context-path: /demo
spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/demo
      username: root
      password: 123123

#Mybatis
mybatis_config_file: mybatis-config.xml
mapper_path: /mapper/**.xml
type_alias_package: io.innofang.springbootpractice.entity